#!/usr/bin/env node
// Redirect http requests to the latest canister ID
// The canister ID is written by running `util/install`.
var http = require("http");
var fs = require("fs");

http.createServer(onRequest).listen(80, () => console.log("I'm listening!"));

function onRequest(client_req, client_res) {
  try {
    let canisterId = fs
      .readFileSync(",canister_id", { encoding: "utf8" })
      .trim();
    let url = `http://localhost:8000/?canisterId=${canisterId}`;
    console.log("serve:", client_req.url, "->", url);

    client_res.writeHead(302, {
      Location: url,
    });
    client_res.end();
  } catch (e) {
    console.log(e.message);
    client_res.writeHead(500);
    client_res.end();
  }
}
